# ConfigMap for Catalog Service Database Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-db-config
  namespace: catalog-service-ns
data:
  DB_HOST: "<RDS_ENDPOINT>"
  DB_PORT: "5432"
  DB_NAME: "catalog_db"
  DB_DRIVER: "org.postgresql.Driver"
  DB_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  DB_SSL_MODE: "require"
